"""initial schema

Revision ID: a6640f53ea52
Revises: 
Create Date: 2026-08-01 14:16:04.905272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6640f53ea52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_admin_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=32), nullable=True),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_created_at'), 'admin_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_read'), 'admin_notifications', ['read'], unique=False)
    op.create_index(op.f('ix_admin_notifications_recipient_admin_id'), 'admin_notifications', ['recipient_admin_id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('active_flow', sa.String(length=64), nullable=True),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('pending_field', sa.String(length=64), nullable=True),
    sa.Column('completed_fields_json', sa.Text(), nullable=False),
    sa.Column('previous_intent', sa.String(length=64), nullable=True),
    sa.Column('last_customer_message', sa.Text(), nullable=True),
    sa.Column('last_bot_response', sa.Text(), nullable=True),
    sa.Column('human_takeover_active', sa.Boolean(), nullable=False),
    sa.Column('takeover_agent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('dashboard_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_events_conversation_id'), 'feature_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feature_events_created_at'), 'feature_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_events_event_name'), 'feature_events', ['event_name'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_reference', sa.String(length=16), nullable=False),
    sa.Column('service_key', sa.String(length=64), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('property_type', sa.String(length=32), nullable=True),
    sa.Column('project_stage', sa.String(length=32), nullable=True),
    sa.Column('timeline', sa.String(length=32), nullable=True),
    sa.Column('budget_range', sa.String(length=32), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('service_area_status', sa.String(length=32), nullable=True),
    sa.Column('email_ciphertext', sa.Text(), nullable=True),
    sa.Column('email_blind_index', sa.String(length=64), nullable=True),
    sa.Column('phone_ciphertext', sa.Text(), nullable=True),
    sa.Column('phone_blind_index', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=16), nullable=True),
    sa.Column('best_contact_time', sa.String(length=64), nullable=True),
    sa.Column('interest_confirmed', sa.Boolean(), nullable=False),
    sa.Column('interest_response', sa.Enum('PENDING', 'YES', 'NO', name='interestresponse', native_enum=False, length=10), nullable=False),
    sa.Column('interest_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interest_confirmation_version', sa.String(length=20), nullable=True),
    sa.Column('safety_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NOT_CONFIRMED', 'NEW', 'ASSIGNED', 'IN_REVIEW', 'CLOSED', name='leadstatus', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_admin_id', sa.String(length=36), nullable=True),
    sa.Column('source_page', sa.String(length=255), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_admin_id'), 'leads', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_leads_conversation_id'), 'leads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leads_email_blind_index'), 'leads', ['email_blind_index'], unique=False)
    op.create_index(op.f('ix_leads_phone_blind_index'), 'leads', ['phone_blind_index'], unique=False)
    op.create_index(op.f('ix_leads_public_reference'), 'leads', ['public_reference'], unique=True)
    op.create_index(op.f('ix_leads_service_key'), 'leads', ['service_key'], unique=False)
    op.create_table('unknown_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempted_service_key', sa.String(length=64), nullable=True),
    sa.Column('attempted_intent', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('linked_faq_id', sa.String(length=64), nullable=True),
    sa.Column('linked_service_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unknown_queries_conversation_id'), 'unknown_queries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_unknown_queries_created_at'), 'unknown_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_unknown_queries_resolved'), 'unknown_queries', ['resolved'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_type', sa.Enum('CALLBACK', 'CONSULTATION', name='appointmenttype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('requested_date', sa.String(length=10), nullable=True),
    sa.Column('time_window', sa.String(length=16), nullable=True),
    sa.Column('customer_timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_conversation_id'), 'appointments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_table('email_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='notificationstatus', native_enum=False, length=12), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_notifications_lead_id'), 'email_notifications', ['lead_id'], unique=False)
    op.create_table('lead_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('contact_consent_given', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_text_version', sa.String(length=20), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('storage_name', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_index(op.f('ix_uploaded_files_lead_id'), 'uploaded_files', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_lead_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('lead_consents')
    op.drop_index(op.f('ix_email_notifications_lead_id'), table_name='email_notifications')
    op.drop_table('email_notifications')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_conversation_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_unknown_queries_resolved'), table_name='unknown_queries')
    op.drop_index(op.f('ix_unknown_queries_created_at'), table_name='unknown_queries')
    op.drop_index(op.f('ix_unknown_queries_conversation_id'), table_name='unknown_queries')
    op.drop_table('unknown_queries')
    op.drop_index(op.f('ix_leads_service_key'), table_name='leads')
    op.drop_index(op.f('ix_leads_public_reference'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_blind_index'), table_name='leads')
    op.drop_index(op.f('ix_leads_email_blind_index'), table_name='leads')
    op.drop_index(op.f('ix_leads_conversation_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_admin_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_feature_events_event_name'), table_name='feature_events')
    op.drop_index(op.f('ix_feature_events_created_at'), table_name='feature_events')
    op.drop_index(op.f('ix_feature_events_conversation_id'), table_name='feature_events')
    op.drop_table('feature_events')
    op.drop_table('dashboard_settings')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_notifications_recipient_admin_id'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_read'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_at'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
